### ISSUE TITLE
Lock screen password input out of box

### ISSUE THREAD

**Issue by akshayG14** [EliverLara/Sweet-kde#19]
The password input in the lockscreen is pushed to the left and out of the password container.
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-47-generic
OS Type: 64-bit

![Screenshot_20200918_162823](https://user-images.githubusercontent.com/18071247/93590406-12117500-f9cc-11ea-831f-99ffbe1c5d1b.png)

**Comment by EliverLara** [comment]
Hi, that should be fixed now, Could you update the 'Sweet' global theme to verify this?

**Comment by akshayG14** [comment]
Hi, have installed theme via Discover and have checked that it is updated to latest version.
Currently, in the login screen the login button is below the input container and the password placeholder and the password text starts from the extreme left edge of the container. When I lock the system, the enter button is to the right of the container and the issue still exists as per the image provided above.
